cmake_minimum_required(VERSION 3.31)
project(Data_Structure_WBI)

set(CMAKE_CXX_STANDARD 20)

# 归档代码
add_executable(1-1 Archive/SeqLinkedList/1.cpp)
add_executable(1-2 Archive/SeqLinkedList/2.cpp)
add_executable(1-3 Archive/SeqLinkedList/3.cpp)
add_executable(1-4 Archive/SeqLinkedList/4.cpp)
add_executable(1-5 Archive/SeqLinkedList/5.cpp)
add_executable(1-6 Archive/SeqLinkedList/6.cpp)
add_executable(1-7 Archive/SeqLinkedList/7.cpp)
add_executable(SeqLinkedList Archive/SeqLinkedList/SeqLinkedList.cpp)
add_executable(Stack Archive/SeqLinkedList/Stack.cpp)
add_executable(2-1 Archive/GeneralizedList/1.cpp)
add_executable(2-2 Archive/GeneralizedList/2.cpp)
add_executable(2-3 Archive/GeneralizedList/3.cpp)
add_executable(2-4 Archive/GeneralizedList/4.cpp)
add_executable(2-5 Archive/GeneralizedList/5.cpp)
add_executable(2-6 Archive/GeneralizedList/6.cpp)
add_executable(insert_sort Archive/insert_sort.cpp)
add_executable(quick_sort Archive/quick_sort.cpp)
add_executable(Sequential-List 第二章-线性表/Sequential-List-fixed.cpp)
